workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: "3.44.3"
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.wafar.user"
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type APP_STORE
      - name: Use signing files
        script: |
          keychain add-certificates
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build ipa for App Store
        script: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
