workflows:
  ios-workflow:
    name: Wafar iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Wafar Codemagic
    environment:
      flutter: "3.44.3"
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.wafar.user"
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type APP_STORE
      - name: Build ipa for App Store
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
