- name: Generate GoogleService-Info.plist
        script: |
          cat << 'EOF' > ios/Runner/GoogleService-Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CLIENT_ID</key>
              <string>حط الكلاينت آي دي بتاعك هنا</string>
              <key>REVERSED_CLIENT_ID</key>
              <string>حط الريفيرست هنا</string>
              <key>API_KEY</key>
              <string>حط الآبي كي هنا</string>
              <key>GCM_SENDER_ID</key>
              <string>حط رقم المرسل هنا</string>
              <key>PLIST_VERSION</key>
              <string>1</string>
              <key>BUNDLE_ID</key>
              <string>com.wafar.user</string>
              <key>PROJECT_ID</key>
              <string>اسم المشروع في فايربيس</string>
              <key>STORAGE_BUCKET</key>
              <string>bucket.appspot.com</string>
              <key>DATABASE_URL</key>
              <string>https://database.firebaseio.com</string>
              <key>SENDER_ID</key>
              <string>رقم المرسل</string>
              <key>APP_ID</key>
              <string>رقم التطبيق</string>
          </dict>
          </plist>
          EOF
          cp ios/Runner/GoogleService-Info.plist ios/GoogleService-Info.plist
